 # schema.yml

version: 2

sources:
  - name: gz_raw_data
    database: data-analytics-ae
    schema: gz_raw_data
    loader: bigquery
    description: test
    tables:
      - name: product
        identifier: raw_gz_product_copy
        description: The price each product_id cost in purchase_price
        columns:
           - name: products_id
             description: ID of the product
           - name: purchSE_PRICE
             description: Selling price of each product
             tests: 
             - not_null
             
      - name: sales
        identifier: raw_gz_sales_copy
        description: sales of Greenweez / we have on row per product_id found in each orders_id
        loaded_at_field: date_date
        columns:
           - name: date_date
             description: date of purchase
           - name: orders_id
             description: ID of the order
           - name: pdt_id
             description: ID of the product
           - name: revenue
             description: Order revenue
           - name: quantity
             description: order quantity 
        tests:
               - unique:
                  column_name: "(orders_id || '-' || pdt_id)"
             # OR ## IF DBT UTILS IS INSTALLED 
               
      - name: ship
        identifier: raw_gz_ship_copy
        description: shipping at Greenweez
        loaded_at_field: orders_id
        columns:
        - name: orders_id
          description: id of the each order
        - name: shipping_fee
          description: the cost of the shipping
        - name: logCost
          description: the cost of all logistics for each order
        - name: ship_cost
          description: the cost of each product shipping
          tests: 
          - not_null

      - name: adwords
        identifier: raw_gz_adwords
        description: adwords campaign data
        loaded_at_field: date_date
        columns:       
        - name: paid_source
          description: Adwords
        - name: campaign_key
          description: the code/key of each campaign per date
        - name: camPGN_name
          description: name of each campaign
        - name: ads_cost
          description: the cost of each campaign 
        - name: impression
          description: number of impressions per campaign
        - name: click
          description: nb of clicks per campaign
          
          
      - name: bing
        identifier: raw_gz_bing
        description: bing campaign data
        loaded_at_field: date_date
        columns:       
        - name: paid_source
          description: Bing
        - name: campaign_key
          description: the code/key of each campaign per date
        - name: camPGN_name
          description: name of each campaign
        - name: ads_cost
          description: the cost of each campaign 
        - name: impression
          description: number of impressions per campaign
        - name: click
          description: nb of clicks per campaign   
        
      - name: criteo
        identifier: raw_gz_criteo
        description: criteo campaign data
        loaded_at_field: date_date
        columns:       
        - name: paid_source
          description: Criteo
        - name: campaign_key
          description: the code/key of each campaign per date
        - name: camPGN_name
          description: name of each campaign
        - name: ads_cost
          description: the cost of each campaign 
        - name: impression
          description: number of impressions per campaign
        - name: click
          description: nb of clicks per campaign   

      - name: facebook
        identifier:  raw_gz_facebook
        description: facebook campaign data
        loaded_at_field: date_date
        columns:       
        - name: paid_source
          description: Facebook
        - name: campaign_key
          description: the code/key of each campaign per date
        - name: camPGN_name
          description: name of each campaign
        - name: ads_cost
          description: the cost of each campaign 
        - name: impression
          description: number of impressions per campaign
        - name: click
          description: nb of clicks per campaign   

SELECT
    camPGN_name as campaign_name,
    cast(ads_cost as float64) as ads_cost
from {{ source('stg_raw_adwords', 'raw_gz_adwords') }} 